#! /bin/sh
#
# qmemserver   Startup script for qmemserver.py
#
# chkconfig: - 85 15
# description: qmemserver is a simple http server to generate and parse cached \
#              xml data from qhost and qstat xml output command
# processname: qmemserver.py

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin

case "$1" in
  start)
    echo "Starting qmemserver"
	qmemserver.py start
	;;
  restart)
    echo "Restarting qmemserver"
    qmemserver.py restart
	;;
  stop)
    echo "Stopping qmemserver"
    qmemserver.py stop
	;;
  *)
	echo "Usage: $0 start|stop|restart" >&2
	exit 3
	;;
esac
